# Generated by Django 5.1.2 on 2024-12-07 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Sport', 'Sport'), ('Business', 'Business'), ('Economy', 'Economy'), ('Lifestyle', 'Lifestyle')], max_length=255, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_img')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
